version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://nsimamfon:QkvGoIqnqGtWILDK@production.8cohh41.mongodb.net/?retryWrites=true&w=majority&appName=production
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
